// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'videoFrame': string;
  'videoViewer': string;
}
export const cssExports: CssExports;
export default cssExports;
