// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'header': string;
  'headerMenu': string;
  'headerTitle': string;
  'headerTitleEnd': string;
}
export const cssExports: CssExports;
export default cssExports;
